#!/usr/bin/env bash
# Downloads the NDI® SDK runtime and puts it where the app build expects it.
#
#   NDI_SDK_ACCEPT_LICENSE=1 scripts/fetch_ndi_sdk.sh android   # -> android/app/src/main/jniLibs/<abi>/libndi.so
#   NDI_SDK_ACCEPT_LICENSE=1 scripts/fetch_ndi_sdk.sh ios       # -> ios/NDI/ + ios/Flutter/NDI.xcconfig (macOS)
#   NDI_SDK_ACCEPT_LICENSE=1 scripts/fetch_ndi_sdk.sh linux     # -> build/ndi/linux/libndi.so (tests)
#
# The NDI SDK is proprietary. Setting NDI_SDK_ACCEPT_LICENSE=1 means you have
# read and accept the NDI SDK license: https://ndi.video/sdk/
# Without the runtime the app still builds; NDI output shows as unavailable.
# NDI® is a registered trademark of Vizrt NDI AB.
set -euo pipefail

target="${1:-}"
root="$(cd "$(dirname "$0")/.." && pwd)"
base="https://downloads.ndi.tv/SDK"

if [ "${NDI_SDK_ACCEPT_LICENSE:-}" != "1" ]; then
  echo "Set NDI_SDK_ACCEPT_LICENSE=1 to accept the NDI SDK license (https://ndi.video/sdk/)." >&2
  exit 2
fi

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# Runs NDI's self-extracting installer non-interactively (it shows the
# license with a pager and asks to accept).
extract_sh() {
  local tgz="$1"
  tar -xzf "$tgz" -C "$work"
  local sh
  sh="$(find "$work" -maxdepth 1 -name 'Install_NDI_SDK_*.sh' | head -1)"
  (cd "$work" && yes | PAGER=cat sh "$sh" > /dev/null)
}

case "$target" in
  android)
    curl -fsSL -o "$work/sdk.tar.gz" "$base/NDI_SDK_Android/Install_NDI_SDK_v6_Android.tar.gz"
    extract_sh "$work/sdk.tar.gz"
    for abi in arm64-v8a armeabi-v7a x86_64; do
      lib="$(find "$work" -path "*/$abi/libndi.so" | head -1)"
      if [ -n "$lib" ]; then
        mkdir -p "$root/android/app/src/main/jniLibs/$abi"
        cp "$lib" "$root/android/app/src/main/jniLibs/$abi/libndi.so"
        echo "NDI runtime: $abi"
      fi
    done
    ;;
  linux)
    curl -fsSL -o "$work/sdk.tar.gz" "$base/NDI_SDK_Linux/Install_NDI_SDK_v6_Linux.tar.gz"
    extract_sh "$work/sdk.tar.gz"
    lib="$(find "$work" -path '*x86_64-linux-gnu/libndi.so*' -type f | head -1)"
    mkdir -p "$root/build/ndi/linux"
    cp "$lib" "$root/build/ndi/linux/libndi.so"
    echo "$root/build/ndi/linux/libndi.so"
    ;;
  ios)
    curl -fsSL -o "$work/sdk.pkg" "$base/NDI_SDK_Mac/Install_NDI_SDK_v6_Apple.pkg"
    pkgutil --expand-full "$work/sdk.pkg" "$work/pkg"
    # Device slice of the iOS static library (plain .a or inside an xcframework).
    lib="$(find "$work/pkg" -path '*ios-arm64/*libndi_ios*.a' | grep -v simulator | head -1)"
    [ -z "$lib" ] && lib="$(find "$work/pkg" -name 'libndi_ios*.a' | head -1)"
    if [ -z "$lib" ]; then echo "libndi_ios not found in the NDI SDK package" >&2; exit 1; fi
    mkdir -p "$root/ios/NDI"
    cp "$lib" "$root/ios/NDI/libndi_ios.a"
    syms=""
    for s in NDIlib_initialize NDIlib_version NDIlib_send_create NDIlib_send_destroy \
             NDIlib_send_send_video_v2 NDIlib_send_send_audio_v2 NDIlib_send_get_no_connections; do
      syms="$syms -Wl,-u,_$s"
    done
    cat > "$root/ios/Flutter/NDI.xcconfig" <<XC
// Generated by scripts/fetch_ndi_sdk.sh: links the NDI runtime into the app.
// Dart loads the symbols with DynamicLibrary.process(), so keep them alive.
OTHER_LDFLAGS = \$(inherited) -force_load "\$(PROJECT_DIR)/NDI/libndi_ios.a" -lc++ -framework Accelerate -framework VideoToolbox$syms
XC
    echo "NDI runtime linked for iOS"
    ;;
  *)
    echo "usage: $0 android|ios|linux" >&2
    exit 2
    ;;
esac
